tarot/coins/urls.py
from django.urls import path

from . import views

app_name = 'coins'
urlpatterns = [
    path(
        'get-bonus-money/',
        views.GetBonusMoneyView.as_view(),
        name='get_bonus_money'
    )
]

tarot/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='home')
]

tarot/tarot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('fortune/', include('fortune.urls', namespace='fortune')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('coins/', include('coins.urls', namespace='coins')),
    ]
if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT
                              )

tarot/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='users/login.html',
             redirect_authenticated_user=True
         ),
         name='login'),
    path('logout/',
         views.CustomLogoutView.as_view(),
         name='logout'),
    path('change-password/',
         auth_views.PasswordChangeView.as_view(
             template_name='users/password_change.html',
             success_url='done/',
         ), name='password_change'),
    path('change-password/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('reset-password/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html',
             email_template_name='users/password_reset_html_email.html',
             success_url='done/',
         ),
         name='password_reset'),
    path('reset-password/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('signup/', views.SignUpFormView.as_view(), name='signup'),
    path('profile/', views.ProfileUpdate.as_view(), name='profile'),
]

tarot/users/models.py
from bisect import bisect

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.safestring import mark_safe
from django_cleanup.signals import cleanup_pre_delete
from sorl.thumbnail import delete, get_thumbnail

from .managers import CustomAccountManager


class Account(AbstractUser):
    class GenderTypes(models.IntegerChoices):
        FEMALE = 1, 'женщина'
        MALE = 2, 'мужчина'

    username = None
    first_name = models.CharField(
        'имя',
        max_length=100
    )
    last_name = models.CharField(
        'фамилия',
        max_length=100
    )
    email = models.EmailField(
        'адрес электронной почты',
        unique=True
    )
    date_of_birth = models.DateField(
        null=True
    )
    custom_username = models.SlugField(
        'ник',
        unique=True,
        null=True,
        blank=True,
        max_length=50,
        help_text='Максимальная длина 50 символов'
    )
    bio = models.CharField(
        null=True,
        blank=True,
        max_length=200,
        help_text='Максимальная длина 200 символов'
    )

    gender = models.IntegerField(
        'пол',
        choices=GenderTypes.choices,
        null=True,
        help_text='Ваш пол'
    )
    profile_picture = models.ImageField(
        'картинка',
        null=True,
        blank=True,
        upload_to='uploads/%Y/%m/'
    )
    timezone = models.CharField(
        'часовой пояс',
        max_length=5,
        null=True
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomAccountManager()

    gender_choices = dict(GenderTypes.choices)

    def get_zodiac_sign(self) -> int:
        if self.date_of_birth:
            day, month = self.date_of_birth.day, self.date_of_birth.month

            signs = [(1, 20, 10), (2, 18, 11), (3, 20, 12), (4, 20, 1),
                     (5, 21, 2), (6, 21, 3), (7, 22, 4), (8, 23, 5),
                     (9, 23, 6), (10, 23, 7), (11, 22, 8), (12, 22, 9),
                     (12, 31, 10)]
            return signs[bisect(signs, (month, day))][2]

    @property
    def zodiac_sign(self) -> str:
        zodiac_dict = {
            1: 'Овен',
            2: 'Телец',
            3: 'Близнецы',
            4: 'Рак',
            5: 'Лев',
            6: 'Дева',
            7: 'Весы',
            8: 'Скорпион',
            9: 'Стрелец',
            10: 'Козерог',
            11: 'Водолей',
            12: 'Рыбы'
        }
        return zodiac_dict.get(self.get_zodiac_sign())

    @property
    def get_profile_pic(self):
        return get_thumbnail(
            self.profile_picture,
            '200x200',
            crop='center',
            quality=31
        )

    def img_tmb(self):
        if self.profile_picture:
            return mark_safe('<img src="%s"' % self.get_profile_pic.url)
        return 'Нет изображения'

    img_tmb.allow_tags = True
    img_tmb.short_description = 'аватар'

    def sorl_delete(**kwargs):
        delete(kwargs['file'])

    cleanup_pre_delete.connect(sorl_delete)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

tarot/users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import Account


class AccountCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = Account
        fields = (Account.email.field.name,)


class AccountChangeForm(UserChangeForm):
    password = None
    required_css_class = 'required'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            if field.field.widget.input_type == 'select':
                field.field.widget.attrs['class'] = 'form-select'
            else:
                field.field.widget.attrs['class'] = 'form-control mb-3'

    class Meta:
        model = Account

        fields = (Account.first_name.field.name,
                  Account.last_name.field.name,
                  Account.custom_username.field.name,
                  Account.bio.field.name,
                  Account.date_of_birth.field.name,
                  Account.gender.field.name,
                  Account.profile_picture.field.name
                  )
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'username': 'Ник',
            'date_of_birth': 'Дата рождения',
            'bio': 'Био',
            'gender': 'Пол',
            'profile_picture': 'Фото профиля'
        }
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'},
                                             format='%Y-%m-%d'),
            'gender': forms.Select(choices=Account.GenderTypes.choices),
            'profile_picture': forms.FileInput(
                attrs={'class': 'form-control'}
            ),
        }
        help_texts = {
            'first_name': 'Укажите имя',
            'last_name': 'Укажите фамилию',
            'gender': 'Укажите пол',
            'date_of_birth': 'Введите дату в формате ДД.ММ.ГГГГ',
            'profile_picture': 'Добавьте фотографию'
        }

tarot/users/views.py
import requests
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from django.views.generic.edit import CreateView

from tarot import settings

from .forms import AccountChangeForm, AccountCreationForm
from .models import Account
from .permissions import CustomLoginRequiredMixin


class SignUpFormView(SuccessMessageMixin, CreateView):
    template_name = 'users/signup.html'
    form_class = AccountCreationForm
    success_url = reverse_lazy('users:profile')
    success_message = 'Вы успешно зарегистрированы'

    def form_valid(self, form):
        form.save()
        user = authenticate(
            username=form.cleaned_data['email'],
            password=form.cleaned_data['password1'],
        )
        login(self.request, user)
        return redirect(self.success_url)


class ProfileUpdate(
    CustomLoginRequiredMixin,
    SuccessMessageMixin,
    UpdateView
):
    model = Account
    form_class = AccountChangeForm
    template_name = 'users/profile.html'
    success_message = 'Данные успешно обновлены'
    success_url = reverse_lazy('users:profile')

    def get_client_ip(self):
        return self.request.META.get('REMOTE_ADDR')

    def get_timezone(self):
        ip_address = self.get_client_ip()
        response = requests.get(f'https://ipapi.co/{ip_address}/json/').json()
        return response.get('timezone')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        timezone = self.get_timezone()
        if timezone:
            form.instance.timezone = timezone
        else:
            form.instance.timezone = settings.TIME_ZONE
        form.save()
        return super().form_valid(form)


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.add_message(request, messages.INFO, 'Вы успешно вышли')
        return response

tarot/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}


        <div class="justify-content-center">
            <form method="post" class="text-light">

                {% include 'users/includes/base_form.html' %}

                <p class="text-center text-light"><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
                <p class="text-center text-light">Нет аккаунта? <a href="{% url 'users:signup' %}">Зарегистрироваться</a></p>
                <div class="text-center text-light">
                    <button type="submit" class="btn btn-success me-2">Войти</button>
                </div>

            </form>


{% endblock %}

tarot/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
    <h2 class="d-flex justify-content-center text-light">Смена пароля</h2>
    <div class="d-flex justify-content-center">
        {% include 'users/includes/super_base_form.html' %}
    </div>

{% endblock %}

tarot/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
    <div class="container rounded bg-white mt-5 mb-5 p-5">
    <h2>Пароль успешно изменен</h2>
    <p>Перейти на <a href="{% url 'homepage:home' %}">главную</a></p>
    </div>
{% endblock %}

tarot/templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}Забыли пароль?{% endblock %}

{% block content %}
    <h1 class="d-flex justify-content-center text-light">Забыли пароль?</h1>
    <p class="d-flex justify-content-center text-light">Введите свою почту и получите инструкции о его восстановлении</p>
    <div class="d-flex justify-content-center">
        {% include 'users/includes/super_base_form.html' %}
    </div>
{% endblock %}

tarot/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Пероль успешно изменен{% endblock %}

{% block content %}
    <div class="container rounded bg-white mt-5 mb-5 p-5">
        <h1>Пароль успешно изменен</h1>
        <p>Ваш пароль успешно изменен. Теперь вы можете зайти на <a href="{% url 'users:login' %}">наш сайт</a>.</p>
    </div>
{% endblock %}

tarot/templates/users/password_reset_confirm.html
{% extends 'base.html' %}


{% block title %}Введите новый пароль{% endblock %}

{% block content %}

    {% if validlink %}

        <h1 class="text-white">Введите новый пароль</h1>
        {% include 'users/includes/super_base_form.html' %}

    {% else %}

        <p>Ссылка для сброса пароля недействительна, потому что она уже использовалась. Пожалуйста, запросите сброс нового
            пароля.</p>

    {% endif %}
{% endblock %}

tarot/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Письмо отправлено{% endblock %}

{% block content %}
    <div class="container rounded bg-white mt-5 mb-5 p-5">
        <h1>Проверьте свою почту</h1>
        <p>Письмо отправлено. Вы получите его в скором времени</p>
    </div>
{% endblock %}

tarot/templates/users/password_reset_html_email.html
{% autoescape off %}
Вы получили это письмо, потому что вы (или кто-то другой) запросили восстановление пароля от учётной записи на сайте localhost:8000, которая связана с этим адресом электронной почты.

Пожалуйста, перейдите на эту страницу и введите новый пароль:
{% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

Ваше имя пользователя (на случай, если вы его забыли): {{ account.email }}

Спасибо, что используете наш сайт!
Команда сайта {{ site_name }}

{% endautoescape %}

tarot/templates/users/profile.html
{% extends 'base.html' %}
{% block title %}Профиль{% endblock %}
{% block content %}
    <div class="container rounded bg-white mt-5 mb-5 p-5">
        <h1 class="text-center text-dark col-12">Ваш магический профиль</h1>
        <div class="row">
            <div class="col-md-3 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                    {% include 'users/user_info.html' %}
                </div>
            </div>
            <div class="col-md-9 border-right">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class="text-right">Настройки профиля</h4>
                    </div>
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <small>Для наибольшей точности предсказаний рекомендуется заполнить все данные профиля</small>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% load static %}
                        <div class="container justify-content-center text-light">
                            {% for field, error in form.errors.items %}
                                <div class="alert alert-danger my-3 p-1" role="alert">
                                    {{ error|striptags }}
                                </div>
                            {% endfor %}
                            {% for field in form %}
                                <label class="text-dark text-center"><b>{{ field.label_tag }}</b></label>
                                {{ field }}
                                {% if field.help_text %}
                                    <p class="text-dark help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            {% endfor %}

                        </div>
                        <br>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>

                    </form>

                </div>
            </div>
        </div>
        <a href="{% url 'users:password_change' %}">
            <button class="btn btn-primary profile-button" type="submit">Сменить пароль</button>
        </a>
    </div>
{% endblock %}

tarot/templates/users/signup.html
{% extends 'base.html' %}


{% block title %}Регистрация{% endblock %}
{% block content %}



<div class="justify-content-center py-3">

    <form method="post" class="text-light">

        {% include 'users/includes/base_form.html' %}

        <div class="text-center text-light">
        <button type="submit" class="btn btn-success me-2">Зарегистрироваться</button>
        </div>
    </form>
  </div>

    <p class="text-center text-light">Уже зарегистрированы? <a href="{% url 'users:login' %}">Войти</a></p>
{% endblock %}

tarot/templates/users/user_info.html
{% if account.profile_picture %}
    <img class="rounded-circle mt-5"
         width="150px"
         src="{{ account.profile_picture.url }}">
{% else %}
    <img class="rounded-circle mt-5"
         width="150px"
         src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg">
{% endif %}
<ul class="list-group d-flex justify-content-start">
    <span class="text-black-50 fw-bold">{{ user.email }}</span>
    {% if account.first_name %}
        <li class="list-group-item rounded-3">Имя: {{ account.get_full_name }}</li>
    {% endif %}
    {% if account.custom_username %}
        <li class="list-group-item">Ник: {{ account.custom_username }}</li>
    {% endif %}
    {% if account.bio %}
        <li class="list-group-item">Био: {{ account.bio }}</li>
    {% endif %}
    {% if account.date_of_birth %}
        <li class="list-group-item">Пол: {{ account.get_gender_display }}</li>
        <li class="list-group-item">Дата рождения: {{ account.date_of_birth }}</li>
        <li class="list-group-item">Знак зодиака: {{ account.zodiac_sign }}</li>
    {% endif %}
</ul>