tarot/coins/urls.py
from django.urls import path

from . import views

app_name = 'coins'
urlpatterns = [
    path(
        'get-bonus-money/',
        views.GetBonusMoneyView.as_view(),
        name='get_bonus_money'
    )
]

tarot/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='home')
]

tarot/tarot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('fortune/', include('fortune.urls', namespace='fortune')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('coins/', include('coins.urls', namespace='coins')),
    ]
if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT
                              )

tarot/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='users/login.html',
             redirect_authenticated_user=True
         ),
         name='login'),
    path('logout/',
         views.CustomLogoutView.as_view(),
         name='logout'),
    path('change-password/',
         auth_views.PasswordChangeView.as_view(
             template_name='users/password_change.html',
             success_url='done/',
         ), name='password_change'),
    path('change-password/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('reset-password/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html',
             email_template_name='users/password_reset_html_email.html',
             success_url='done/',
         ),
         name='password_reset'),
    path('reset-password/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('signup/', views.SignUpFormView.as_view(), name='signup'),
    path('profile/', views.ProfileUpdate.as_view(), name='profile'),
]

tarot/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        {% block static %}{% endblock %}
        <link rel="stylesheet" href="{% static "main.css" %}">
        <link rel="stylesheet"
              href="{% static "./bootstrap/css/bootstrap.min.css" %}">
        <title>
            {% block title %}{% endblock %}
        </title>
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{% static 'favicons/apple-touch-icon.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{% static 'favicons/favicon-32x32.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{% static 'favicons/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'favicons/site.webmanifest' %}">
        <link rel="mask-icon"
              href="{% static 'favicons/safari-pinned-tab.svg' %}"
              color="#5bbad5">
        <link rel="shortcut icon" href="{% static 'favicons/favicon.ico' %}">
        <meta name="msapplication-TileColor" content="#b91d47">
        <meta name="msapplication-config"
              content="{% static 'favicons/browserconfig.xml' %}">
        <meta name="theme-color" content="#ffffff">
        <style>
        body {
            background-color: #2F242C;
        }
        </style>
    </head>
    <body style="background: #2F242C;">
        <header>
            <div class="container mb-4 mt-2">
                <div class="d-flex justify-content-between">
                    <div class="navbar-header fixed-brand menu">
                        <a href="">
                            <button type="button"
                                    class="navbar-toggle collapsed rounded-5 py-2 px-3"
                                    data-toggle="collapse"
                                    id="menu-toggle"
                                    style="background: #3E3545;
                                           border-color: #1f042d">
                                <span style="color: #FEEBC7">Menu</span>
                            </button>
                        </a>
                    </div>
                    <a class="navbar-brand mx-5 fs-3 fw-normal"
                       href="{% url 'homepage:home' %}"
                       style="color: #FEEBC7">ONLINE
                    TAROT</a>
                    {% if user.is_authenticated %}
                        <a class="btn btn-outline-light"
                           href="{% url 'coins:get_bonus_money' %}">Бонусные монетки
                            <br/>
                            <span class="fs-6">{{ bonus_status }}</span>
                        </a>
                        <div class="rounded-5 px-4 py-2 " style="background: #1E1E1E">
                            <span class="fw-light fs-5 text-light">{{ balance }}🪙</span>
                            <span class="text-light me-2 fs-5"></span>
                            <a href="{% url 'users:profile' %}"><strong class="text-light text-decoration-none">{{ user.email }}</strong></a>
                            {% if user.profile_picture %}
                                <img src="{{ user.profile_picture.url }}"
                                     alt=""
                                     width="53"
                                     height="53"
                                     class="rounded-circle mx-2">
                            {% else %}
                                <img src="{% static 'users/blank_user_picture.png' %}"
                                     alt=""
                                     width="53"
                                     height="53"
                                     class="rounded-circle mx-2">
                            {% endif %}
                            <a class="text-danger text-decoration-none"
                               href="{% url 'users:logout' %}">Выйти</a>
                        </div>
                    {% else %}
                        <div>
                            <a class="btn btn-success me-2" href="{% url "users:login" %}">Вход</a>
                            <a class="btn btn-light" href="{% url "users:signup" %}">Регистрация</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </header>
        {% if messages %}
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show bg-light"
                                 role="alert">
                                {{ message }}
                                <button type="button"
                                        class="btn-close"
                                        data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
        <div id="wrapper">
            <div id="sidebar-wrapper" style="background: #3E3545;">
                <ul class="sidebar-nav nav-pills nav-stacked py-5 ps-5" id="menu">
                    <li class="my-5">
                        <a href="{% url 'homepage:home' %}">
                            <span class="fs-3">Главная</span>
                        </a>
                    </li>
                    <li class="my-5">
                        <a href="#">
                            <span class="fs-3">Таропедия</span>
                        </a>
                    </li>
                    <li class="my-5">
                        <a href="#">
                            <span class="fs-3">История</span>
                        </a>
                    </li>
                    <li class="my-5">
                        <a href="{% url 'users:profile' %}">
                            <span class="fs-3">Аккаунт</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="inner" id="no_active_content"></div>
        <div class="inner" id="content">
            {% block content %}{% endblock %}
            <footer class="container position-relative p-4 text-light">
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">© 2022 Copyright: TAROT ONLINE</div>
            </footer>
        </div>
        <script type="text/javascript"
                src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
        <script type="text/javascript" defer src="{% static "main.js" %}"></script>
        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </body>
</html>